# Generated by Django 4.1.4 on 2022-12-21 05:51

import ImageDetection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=ImageDetection.models.upload_image
                    ),
                ),
                (
                    "model_evaluation",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
        ),
    ]
